package com.xiaozhi.watch;

/**
 * 情绪球 41 种表情配置 —— 由 tools/gen_eb_java.js 从 NX_emotion-ball/js/emotions.js
 * （基底 32 种）+ app/new_emotions.json（自定义 9 种）自动生成。
 * <b>请勿手改</b>，要改表情请改源文件后重新生成。
 *
 * <p>嵌套结构翻译成 Java 字面量既啰嗦又易错，而 Android 自带 org.json，
 * 所以这里直接内嵌 JSON、运行时解析（只在首次取用时解析一次）。</p>
 *
 * <p>已剔除 desc / en 文案：手表屏幕只有 186x215dp，显示不下，引擎也不消费。</p>
 *
 * <p>ID 分段：00-09 生命周期 · 10-29 情绪反应 · 30-49 代理工作状态 · 50+ 自定义。</p>
 */
public final class Emotions {

    /** 41 种表情的完整配置（JSON 数组，含 50+ 自定义段） */
    public static final String JSON =
            "[{\"id\":\"00\",\"name\":\"\u7761\u7720\",\"group\":\"life\",\"transition\":900,\"gaze\":false,\"pool\":[13,22,4],\"poolMs\":[6000"
            +             ",10000],\"blinkMs\":null,\"openness\":0.08,\"body\":{\"y\":4,\"rotate\":-2,\"breathe\":0.018,\"color\":\"#EEEBE4\",\""
            +             "zzz\":1},\"eyes\":{\"both\":{\"y\":4,\"lookY\":2}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":1"
            +             ".2,\"period\":3600}]},{\"id\":\"01\",\"name\":\"\u5524\u9192\",\"group\":\"life\",\"transition\":320,\"pool\":[13],\"poolMs\":[800"
            +             ",800],\"blinkMs\":null,\"sequence\":{\"settle\":{\"next\":\"02\"},\"frames\":[{\"at\":0,\"eyes\":{\"both\":{\"open\":0.1"
            +             ",\"y\":4}}},{\"at\":420,\"eyes\":{\"left\":{\"open\":0.55,\"y\":2},\"right\":{\"open\":0.12,\"y\":4}}},{\"at\":820,\"eyes"
            +             "\":{\"both\":{\"open\":0.3,\"y\":3}}},{\"at\":1400,\"eyes\":{\"both\":{\"open\":1,\"scaleX\":1.12,\"scaleY\":1.12,\"y\":-"
            +             "2}}},{\"at\":2100,\"eyes\":{\"both\":{\"open\":1,\"y\":0}}}]}},{\"id\":\"02\",\"name\":\"\u5f85\u673a\u653e\u7a7a\",\"group\":\"life\",\"transi"
            +             "tion\":700,\"pool\":[0,8],\"poolMs\":[9000,16000],\"blinkMs\":[6000,14000],\"antics\":true,\"body\":{\"breathe\":"
            +             "0.012},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"glance\",\"amp\":10,\"period\":4800},{\"target\":\"e"
            +             "yes\",\"prop\":\"lookY\",\"type\":\"sine\",\"amp\":2,\"period\":4100,\"phase\":1.1}]},{\"id\":\"03\",\"name\":\"\u597d\u5947\",\"group"
            +             "\":\"life\",\"transition\":420,\"pool\":[3,21,0,15],\"poolMs\":[1800,3200],\"blinkMs\":[2500,5500],\"body\":{\"rot"
            +             "ate\":4,\"breathe\":0.01},\"eyes\":{\"both\":{\"lookY\":-1}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":"
            +             "\"sine\",\"amp\":2.4,\"period\":2800}]},{\"id\":\"04\",\"name\":\"\u53d1\u5446\",\"group\":\"life\",\"transition\":800,\"pool\":[4,2"
            +             "2,0],\"poolMs\":[3500,6000],\"blinkMs\":[4000,8000],\"antics\":true,\"body\":{\"rotate\":-3,\"breathe\":0.008},\""
            +             "eyes\":{\"left\":{\"lookX\":-4,\"lookY\":2},\"right\":{\"lookX\":5,\"lookY\":-1}},\"anims\":[{\"target\":\"eyes\",\"prop"
            +             "\":\"lookX\",\"type\":\"sine\",\"amp\":3,\"period\":6800}]},{\"id\":\"05\",\"name\":\"\u52a0\u8f7d\u82cf\u9192\",\"group\":\"life\",\"transition"
            +             "\":480,\"pool\":[0,8],\"poolMs\":[6000,10000],\"blinkMs\":null,\"anims\":[{\"target\":\"left\",\"prop\":\"open\",\"typ"
            +             "e\":\"blink\",\"interval\":1600,\"dur\":700},{\"target\":\"right\",\"prop\":\"open\",\"type\":\"blink\",\"interval\":1600"
            +             ",\"dur\":700,\"phaseMs\":800},{\"target\":\"eyes\",\"prop\":\"scale\",\"type\":\"pulse\",\"amp\":0.04,\"period\":1600}]}"
            +             ",{\"id\":\"06\",\"name\":\"\u4f11\u7720\",\"group\":\"life\",\"transition\":1200,\"gaze\":false,\"pool\":[4,22,13],\"poolMs\":[400"
            +             "0,8000],\"blinkMs\":null,\"openness\":0.4,\"body\":{\"y\":6,\"scale\":0.98,\"rotate\":-1,\"breathe\":0.005,\"color\""
            +             ":\"#EBE8E1\"},\"eyes\":{\"both\":{\"y\":5}}},{\"id\":\"07\",\"name\":\"\u6296\u52a8\u5524\u9192\",\"group\":\"life\",\"transition\":220,\"pool\""
            +             ":[13],\"poolMs\":[800,800],\"blinkMs\":null,\"body\":{\"breathe\":0.004},\"anims\":[{\"target\":\"body\",\"prop\":\"x"
            +             "\",\"type\":\"jitter\",\"amp\":4.5,\"speed\":10,\"decay\":1600},{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"jitter"
            +             "\",\"amp\":3,\"speed\":8,\"decay\":1600}],\"sequence\":{\"settle\":{\"next\":\"02\"},\"frames\":[{\"at\":0,\"eyes\":{\"bot"
            +             "h\":{\"open\":0.1}}},{\"at\":380,\"eyes\":{\"left\":{\"open\":0.4},\"right\":{\"open\":0.12}}},{\"at\":900,\"eyes\":{\"b"
            +             "oth\":{\"open\":0.7,\"y\":1}}},{\"at\":1600,\"eyes\":{\"both\":{\"open\":1,\"scaleX\":1.08,\"scaleY\":1.08,\"y\":-1}}}]"
            +             "}},{\"id\":\"10\",\"name\":\"\u5f00\u5fc3\",\"group\":\"emotion\",\"transition\":380,\"pool\":[2,11,17,19],\"poolMs\":[2500,4500"
            +             "],\"blinkMs\":[2500,5000],\"antics\":true,\"body\":{\"y\":-3,\"breathe\":0.014,\"color\":\"#F6EFE4\"},\"eyes\":{\"bot"
            +             "h\":{\"y\":-3}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"glance\",\"amp\":6,\"period\":3000},{\"targe"
            +             "t\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":2.2,\"period\":1400}]},{\"id\":\"11\",\"name\":\"\u7591\u60d1\",\"group\":\"emotio"
            +             "n\",\"transition\":420,\"pool\":[14,5,8],\"poolMs\":[2200,3800],\"blinkMs\":[2800,5500],\"body\":{\"rotate\":-8,\""
            +             "breathe\":0.008},\"eyes\":{\"left\":{\"y\":-4,\"scaleX\":1.1,\"scaleY\":1.1},\"right\":{\"y\":3,\"scaleX\":0.9,\"scale"
            +             "Y\":0.9,\"lookX\":3}},\"anims\":[{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\",\"amp\":1.4,\"period\":3200}]"
            +             "},{\"id\":\"12\",\"name\":\"\u5931\u843d\",\"group\":\"emotion\",\"transition\":820,\"pool\":[4,13,22],\"poolMs\":[4000,7000],\"b"
            +             "linkMs\":[4000,8000],\"body\":{\"y\":5,\"rotate\":-4,\"breathe\":0.007,\"color\":\"#EDEAE3\"},\"eyes\":{\"both\":{\"y\""
            +             ":8,\"scaleX\":0.88,\"scaleY\":0.88,\"lookY\":4}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":"
            +             "1.6,\"period\":3600}]},{\"id\":\"13\",\"name\":\"\u60ca\u8bb6\",\"group\":\"emotion\",\"transition\":180,\"pool\":[3,21],\"poolMs"
            +             "\":[2500,4000],\"blinkMs\":[1800,3500],\"body\":{\"y\":-4,\"scale\":1.03,\"breathe\":0.006},\"eyes\":{\"both\":{\"sc"
            +             "aleX\":1.14,\"scaleY\":1.14,\"y\":-2,\"lookY\":-2}},\"sequence\":{\"settle\":\"base\",\"frames\":[{\"at\":0,\"eyes\":{\""
            +             "both\":{\"scaleX\":0.92,\"scaleY\":0.92}}},{\"at\":150,\"eyes\":{\"both\":{\"scaleX\":1.45,\"scaleY\":1.45,\"y\":-4}}"
            +             ",\"body\":{\"y\":-7,\"scale\":1.05}},{\"at\":420,\"eyes\":{\"both\":{\"scaleX\":1.22,\"scaleY\":1.22,\"y\":-3}}}]}},{\""
            +             "id\":\"14\",\"name\":\"\u5bb3\u7f9e\",\"group\":\"emotion\",\"transition\":560,\"pool\":[0,24,13],\"poolMs\":[3000,5500],\"blink"
            +             "Ms\":[3000,6000],\"body\":{\"rotate\":6,\"breathe\":0.012,\"color\":\"#F4D3D0\"},\"eyes\":{\"both\":{\"y\":4,\"lookX\":"
            +             "8,\"lookY\":3}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"sine\",\"amp\":2,\"period\":2600}],\"sequen"
            +             "ce\":{\"settle\":\"hold\",\"frames\":[{\"at\":0,\"body\":{\"color\":\"#F3F0EA\"}},{\"at\":1500,\"body\":{\"color\":\"#F4D3"
            +             "D0\"}}]}},{\"id\":\"15\",\"name\":\"\u75b2\u60eb\",\"group\":\"emotion\",\"transition\":900,\"pool\":[4,22,13],\"poolMs\":[4000,8"
            +             "000],\"blinkMs\":null,\"openness\":0.55,\"body\":{\"y\":4,\"rotate\":-3,\"breathe\":0.016,\"color\":\"#EFECE5\"},\"ey"
            +             "es\":{\"both\":{\"y\":5,\"lookY\":3}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"open\",\"type\":\"sine\",\"amp\":0.06,\"per"
            +             "iod\":3400}]},{\"id\":\"16\",\"name\":\"\u4e13\u6ce8\",\"group\":\"emotion\",\"transition\":320,\"pool\":[7,16,11,10],\"poolMs\":"
            +             "[1800,3200],\"blinkMs\":[2800,5500],\"body\":{\"breathe\":0.004},\"eyes\":{\"left\":{\"x\":4},\"right\":{\"x\":-4}}}"
            +             ",{\"id\":\"17\",\"name\":\"\u614c\u5f20\",\"group\":\"emotion\",\"transition\":200,\"pool\":[3,21],\"poolMs\":[900,1800],\"blinkM"
            +             "s\":[1200,3000],\"body\":{\"breathe\":0.006},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"jitter\",\"am"
            +             "p\":6,\"speed\":11},{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"jitter\",\"amp\":4,\"speed\":9},{\"target\":\"body\""
            +             ",\"prop\":\"x\",\"type\":\"jitter\",\"amp\":1.6,\"speed\":8}]},{\"id\":\"18\",\"name\":\"\u65e0\u5948\",\"group\":\"emotion\",\"transit"
            +             "ion\":560,\"pool\":[14,5,23],\"poolMs\":[2600,4500],\"blinkMs\":[4500,8000],\"body\":{\"rotate\":10,\"y\":2,\"brea"
            +             "the\":0.01},\"eyes\":{\"both\":{\"lookX\":7,\"lookY\":-8}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"s"
            +             "ine\",\"amp\":1.6,\"period\":3000},{\"target\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":1.2,\"period\":3000}]},{"
            +             "\"id\":\"19\",\"name\":\"\u6ee1\u610f\",\"group\":\"emotion\",\"transition\":580,\"pool\":[15,8,2],\"poolMs\":[3500,6000],\"blink"
            +             "Ms\":[3500,7000],\"antics\":true,\"body\":{\"breathe\":0.012,\"color\":\"#F5EFE6\"},\"anims\":[{\"target\":\"eyes\",\""
            +             "prop\":\"y\",\"type\":\"sine\",\"amp\":5,\"period\":1050},{\"target\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":1.6,\""
            +             "period\":1050,\"phase\":0.6}]},{\"id\":\"20\",\"name\":\"\u56f0\u60d1\",\"group\":\"emotion\",\"transition\":480,\"pool\":[14,5,8"
            +             "],\"poolMs\":[2200,3800],\"blinkMs\":[2800,5500],\"body\":{\"rotate\":-5,\"breathe\":0.008},\"eyes\":{\"left\":{\"s"
            +             "caleX\":1.16,\"scaleY\":1.16,\"y\":-3,\"lookX\":-3},\"right\":{\"scaleX\":0.8,\"scaleY\":0.8,\"y\":4,\"lookX\":5}},\"a"
            +             "nims\":[{\"target\":\"left\",\"prop\":\"lookX\",\"type\":\"sine\",\"amp\":2.5,\"period\":3200},{\"target\":\"right\",\"pro"
            +             "p\":\"lookX\",\"type\":\"sine\",\"amp\":2.5,\"period\":3200,\"phase\":1.6}]},{\"id\":\"21\",\"name\":\"\u751f\u6c14\",\"group\":\"emot"
            +             "ion\",\"transition\":260,\"pool\":[7,16],\"poolMs\":[2200,3800],\"blinkMs\":[3500,7000],\"body\":{\"y\":1,\"breath"
            +             "e\":0.004,\"color\":\"#E4574A\"},\"anims\":[{\"target\":\"body\",\"prop\":\"x\",\"type\":\"jitter\",\"amp\":1.1,\"speed\":7"
            +             "}],\"sequence\":{\"settle\":\"hold\",\"frames\":[{\"at\":0,\"body\":{\"color\":\"#F3F0EA\"}},{\"at\":250,\"body\":{\"colo"
            +             "r\":\"#E4574A\"}}]}},{\"id\":\"30\",\"name\":\"\u601d\u8003\u4e2d\",\"group\":\"agent\",\"transition\":480,\"pool\":[8,16,14,17,5],\"po"
            +             "olMs\":[2000,3600],\"blinkMs\":[3500,7000],\"body\":{\"rotate\":-3,\"breathe\":0.01,\"orbit\":1},\"eyes\":{\"both\""
            +             ":{\"lookY\":-6,\"y\":-2}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"sine\",\"amp\":9,\"period\":2600}]"
            +             "},{\"id\":\"31\",\"name\":\"\u63a5\u6536\u4efb\u52a1\",\"group\":\"agent\",\"transition\":220,\"pool\":[19,0,8],\"poolMs\":[4000,8000],\"bl"
            +             "inkMs\":null,\"body\":{\"breathe\":0.008},\"sequence\":{\"settle\":\"base\",\"frames\":[{\"at\":0},{\"at\":100,\"eyes\""
            +             ":{\"both\":{\"open\":0.1}}},{\"at\":280,\"eyes\":{\"both\":{\"open\":1,\"scaleX\":1.12,\"scaleY\":1.12,\"y\":-2}},\"bod"
            +             "y\":{\"y\":-3}},{\"at\":700,\"eyes\":{\"both\":{\"open\":1}}}]}},{\"id\":\"32\",\"name\":\"\u5904\u7406\u4e2d\u5fd9\u788c\",\"group\":\"agent\",\"tra"
            +             "nsition\":360,\"pool\":[7,16,11,10],\"poolMs\":[1800,3200],\"blinkMs\":[2800,5500],\"body\":{\"breathe\":0.008}"
            +             ",\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"sine\",\"amp\":6,\"period\":1200},{\"target\":\"eyes\",\"pro"
            +             "p\":\"lookY\",\"type\":\"sine\",\"amp\":4,\"period\":900,\"phase\":0.8}]},{\"id\":\"33\",\"name\":\"\u4efb\u52a1\u5b8c\u6210\",\"group\":\"agent"
            +             "\",\"transition\":240,\"pool\":[2,8,17],\"poolMs\":[1400,2600],\"blinkMs\":[2200,4500],\"body\":{\"ribbons\":1,\"c"
            +             "onfetti\":0.95},\"eyes\":{\"both\":{\"y\":-3}},\"sequence\":{\"settle\":\"base\",\"frames\":[{\"at\":0,\"body\":{\"y\":0}"
            +             "},{\"at\":300,\"eyes\":{\"both\":{\"scaleX\":1.1,\"scaleY\":1.1,\"y\":-5}},\"body\":{\"y\":-6}},{\"at\":700,\"eyes\":{\"b"
            +             "oth\":{\"scaleX\":1.05,\"scaleY\":1.05,\"y\":-4}},\"body\":{\"y\":-2}},{\"at\":1100,\"body\":{\"y\":0}}]}},{\"id\":\"34\""
            +             ",\"name\":\"\u51fa\u9519\",\"group\":\"agent\",\"transition\":220,\"pool\":[3,21],\"poolMs\":[2000,3600],\"blinkMs\":null,\"bod"
            +             "y\":{\"rotate\":-6,\"color\":\"#E25B5B\"},\"eyes\":{\"left\":{\"y\":-3,\"rotate\":-6},\"right\":{\"y\":4,\"rotate\":8}},\""
            +             "anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\"type\":\"jitter\",\"amp\":1.4,\"speed\":8,\"decay\":800}],\"sequence\""
            +             ":{\"settle\":\"hold\",\"frames\":[{\"at\":0,\"body\":{\"color\":\"#E25B5B\",\"rotate\":-6}},{\"at\":170,\"body\":{\"color"
            +             "\":\"#F6F3EC\",\"rotate\":-4}},{\"at\":340,\"body\":{\"color\":\"#E25B5B\",\"rotate\":-7}},{\"at\":510,\"body\":{\"color"
            +             "\":\"#F6F3EC\",\"rotate\":-5}},{\"at\":700,\"body\":{\"color\":\"#DE5555\",\"rotate\":-6}}]}},{\"id\":\"35\",\"name\":\"\u7b49\u5f85"
            +             "\u8f93\u5165\",\"group\":\"agent\",\"transition\":480,\"pool\":[10,1,19],\"poolMs\":[2800,5000],\"blinkMs\":[3000,7000],\"bo"
            +             "dy\":{\"breathe\":0.01},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"sine\",\"amp\":6,\"period\":2200}]}"
            +             ",{\"id\":\"36\",\"name\":\"\u8054\u7f51\u52a0\u8f7d\",\"group\":\"agent\",\"transition\":380,\"pool\":[0,8],\"poolMs\":[6000,10000],\"blink"
            +             "Ms\":null,\"anims\":[{\"target\":\"left\",\"prop\":\"open\",\"type\":\"blink\",\"interval\":1200,\"dur\":380},{\"target\""
            +             ":\"right\",\"prop\":\"open\",\"type\":\"blink\",\"interval\":1200,\"dur\":380,\"phaseMs\":600},{\"target\":\"eyes\",\"pro"
            +             "p\":\"lookX\",\"type\":\"sine\",\"amp\":2,\"period\":2400}]},{\"id\":\"37\",\"name\":\"\u590d\u8ff0\u56de\u5fc6\",\"group\":\"agent\",\"transiti"
            +             "on\":780,\"pool\":[10,1,19],\"poolMs\":[4000,8000],\"blinkMs\":null,\"body\":{\"rotate\":-2,\"breathe\":0.009},\"e"
            +             "yes\":{\"both\":{\"lookY\":-9,\"lookX\":3,\"y\":-3}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"sine\",\""
            +             "amp\":2.4,\"period\":4000}]},{\"id\":\"38\",\"name\":\"\u62d2\u7edd/\u53d7\u9650\",\"group\":\"agent\",\"transition\":380,\"pool\":[14,5,23"
            +             "],\"poolMs\":[2600,4500],\"blinkMs\":[4500,8000],\"openness\":0.6,\"body\":{\"y\":2,\"rotate\":-2,\"color\":\"#EFE8"
            +             "E4\"},\"eyes\":{\"both\":{\"lookY\":3,\"y\":2}},\"sequence\":{\"settle\":\"base\",\"frames\":[{\"at\":0,\"body\":{\"x\":0}}"
            +             ",{\"at\":130,\"body\":{\"x\":-9,\"rotate\":-6}},{\"at\":300,\"body\":{\"x\":8,\"rotate\":2}},{\"at\":470,\"body\":{\"x\":-"
            +             "6,\"rotate\":-5}},{\"at\":630,\"body\":{\"x\":4,\"rotate\":0}},{\"at\":800,\"body\":{\"x\":0,\"rotate\":-2}}]}},{\"id\":"
            +             "\"39\",\"name\":\"\u8f93\u51fa\u56de\u590d\",\"group\":\"agent\",\"transition\":360,\"pool\":[15,9],\"poolMs\":[4000,8000],\"blinkMs\":nul"
            +             "l,\"body\":{\"breathe\":0.008},\"eyes\":{\"both\":{\"y\":-2}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"scale\",\"type\":"
            +             "\"pulse\",\"amp\":0.1,\"period\":680},{\"target\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":1.2,\"period\":680}]},"
            +             "{\"id\":\"40\",\"name\":\"\u68c0\u7d22\u8d44\u6599\",\"group\":\"agent\",\"transition\":320,\"pool\":[15,9,3,20,12,18],\"poolMs\":[1000,18"
            +             "00],\"poolSpeed\":10,\"blinkMs\":[1600,4000],\"body\":{\"breathe\":0.006},\"anims\":[{\"target\":\"eyes\",\"prop\":\""
            +             "lookX\",\"type\":\"scan\",\"amp\":11,\"period\":700}]},{\"id\":\"41\",\"name\":\"\u505c\u6b62\u7ec8\u6b62\",\"group\":\"agent\",\"transition\":"
            +             "280,\"gaze\":false,\"pool\":[13,22],\"poolMs\":[6000,9000],\"blinkMs\":null,\"body\":{\"y\":3,\"breathe\":0.004,\"c"
            +             "olor\":\"#EBE8E2\"},\"sequence\":{\"settle\":\"hold\",\"frames\":[{\"at\":0},{\"at\":1500,\"eyes\":{\"both\":{\"scaleX\":"
            +             "0.6,\"scaleY\":0.6,\"open\":0.35,\"y\":3}},\"body\":{\"y\":4,\"scale\":0.97}}]}},{\"id\":\"50\",\"name\":\"\u5fc3\u75bc\u5b89\u629a\",\"group"
            +             "\":\"custom\",\"transition\":520,\"pool\":[10,1],\"poolMs\":[4200,7000],\"blinkMs\":[4500,8000],\"openness\":0.88"
            +             ",\"body\":{\"y\":5,\"rotate\":-7,\"breathe\":0.008,\"color\":\"#F3E7E2\"},\"eyes\":{\"left\":{\"open\":0.62,\"y\":6,\"loo"
            +             "kY\":4},\"right\":{\"y\":4,\"lookY\":4,\"scaleY\":1.06}},\"anims\":[{\"target\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\""
            +             "amp\":2.8,\"period\":1600},{\"target\":\"eyes\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":1.1,\"period\":1600,\"phase\":0."
            +             "5}]},{\"id\":\"51\",\"name\":\"\u540c\u4ec7\u654c\u5ffe\",\"group\":\"custom\",\"transition\":300,\"pool\":[7,16],\"poolMs\":[3600,6000],\""
            +             "blinkMs\":[4000,7500],\"openness\":0.78,\"body\":{\"y\":-2,\"scale\":1.02,\"breathe\":0.018,\"color\":\"#B95A4E\"},"
            +             "\"eyes\":{\"left\":{\"rotate\":10,\"y\":-1,\"scaleX\":1.04,\"scaleY\":0.92},\"right\":{\"rotate\":-10,\"y\":-1,\"scaleX"
            +             "\":1.04,\"scaleY\":0.92}},\"anims\":[{\"target\":\"body\",\"prop\":\"x\",\"type\":\"jitter\",\"amp\":0.7,\"speed\":4},{\"t"
            +             "arget\":\"body\",\"prop\":\"y\",\"type\":\"sine\",\"amp\":0.8,\"period\":2200}]},{\"id\":\"52\",\"name\":\"\u60ac\u5fc3\u62c5\u5fe7\",\"group\":\""
            +             "custom\",\"transition\":240,\"pool\":[3,21],\"poolMs\":[3000,5200],\"blinkMs\":[1400,2800],\"openness\":1,\"body"
            +             "\":{\"y\":-3,\"rotate\":-4,\"breathe\":0.003,\"color\":\"#E9E6DF\"},\"eyes\":{\"both\":{\"lookY\":-2,\"y\":-1},\"left\":{"
            +             "\"scaleY\":1.12},\"right\":{\"scaleY\":0.98}},\"anims\":[{\"target\":\"body\",\"prop\":\"x\",\"type\":\"jitter\",\"amp\":1"
            +             ",\"speed\":5},{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"sine\",\"amp\":1.2,\"period\":2600,\"phase\":0.8}]},{\"i"
            +             "d\":\"53\",\"name\":\"\u65e0\u8bed\u51dd\u564e\",\"group\":\"custom\",\"transition\":900,\"gaze\":false,\"pool\":[13,4],\"poolMs\":[5000,80"
            +             "00],\"blinkMs\":null,\"openness\":1,\"body\":{\"y\":6,\"rotate\":-3,\"breathe\":0.005,\"color\":\"#E7E5E1\"},\"eyes\":"
            +             "{\"both\":{\"open\":0.35,\"y\":6,\"lookY\":4}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"open\",\"type\":\"blink\",\"inter"
            +             "val\":2800,\"dur\":650,\"depth\":0.3},{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\",\"amp\":1.8,\"period\":5"
            +             "200}]},{\"id\":\"54\",\"name\":\"\u51d1\u8fd1\u7ec6\u542c\",\"group\":\"custom\",\"transition\":260,\"pool\":[10,1],\"poolMs\":[3400,5600]"
            +             ",\"blinkMs\":[2600,5200],\"openness\":1,\"body\":{\"y\":-5,\"scale\":1.06,\"rotate\":-6,\"breathe\":0.006},\"eyes\":"
            +             "{\"both\":{\"lookY\":-2},\"left\":{\"open\":1.05},\"right\":{\"open\":0.45,\"y\":1}},\"anims\":[{\"target\":\"body\",\"pr"
            +             "op\":\"x\",\"type\":\"sine\",\"amp\":2.5,\"period\":2400}]},{\"id\":\"55\",\"name\":\"\u5361\u58f3\u5192\u70df\",\"group\":\"custom\",\"transiti"
            +             "on\":180,\"pool\":[3,21],\"poolMs\":[650,1100],\"poolSpeed\":10,\"blinkMs\":null,\"openness\":1.08,\"body\":{\"y\":"
            +             "-1,\"breathe\":0.004,\"color\":\"#E4E1DB\"},\"eyes\":{\"left\":{\"lookX\":7,\"scaleX\":1.22,\"scaleY\":1.22},\"right\""
            +             ":{\"lookX\":-7,\"scaleX\":0.72,\"scaleY\":0.72}},\"anims\":[{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\",\""
            +             "amp\":2.6,\"period\":1300},{\"target\":\"body\",\"prop\":\"x\",\"type\":\"jitter\",\"amp\":1.6,\"speed\":10}]},{\"id\":\"5"
            +             "6\",\"name\":\"\u56db\u5904\u5f20\u671b\",\"group\":\"custom\",\"transition\":420,\"pool\":[15,9,20,12,18],\"poolMs\":[1100,2000],\"blin"
            +             "kMs\":[2200,4600],\"openness\":1,\"antics\":true,\"body\":{\"breathe\":0.012},\"eyes\":{\"both\":{\"lookY\":-1}},\"a"
            +             "nims\":[{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\",\"amp\":5,\"period\":5200},{\"target\":\"eyes\",\"prop\""
            +             ":\"lookX\",\"type\":\"scan\",\"amp\":12,\"period\":2800}]},{\"id\":\"57\",\"name\":\"\u5077\u7784\u88c5\u6ca1\u4e8b\",\"group\":\"custom\",\"transit"
            +             "ion\":400,\"pool\":[24,14,5],\"poolMs\":[2600,4200],\"blinkMs\":[5000,9000],\"openness\":0.95,\"body\":{\"rotate"
            +             "\":2,\"breathe\":0.01},\"eyes\":{\"both\":{\"lookX\":4,\"lookY\":2}},\"anims\":[{\"target\":\"eyes\",\"prop\":\"lookX\",\""
            +             "type\":\"glance\",\"amp\":8,\"period\":4600},{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\",\"amp\":3,\"period"
            +             "\":4600,\"phase\":0.4},{\"target\":\"eyes\",\"prop\":\"open\",\"type\":\"blink\",\"interval\":4600,\"dur\":420,\"depth\":"
            +             "1,\"phaseMs\":1300}]},{\"id\":\"58\",\"name\":\"\u88ab\u6253\u65ad\u61f5\",\"group\":\"custom\",\"transition\":150,\"pool\":[13,3],\"poolMs"
            +             "\":[1000,1800],\"blinkMs\":null,\"body\":{\"y\":-2,\"scale\":0.97,\"rotate\":-2,\"breathe\":0.004,\"color\":\"#EFEBE"
            +             "5\"},\"eyes\":{\"left\":{\"open\":1.1,\"scaleX\":1.05,\"scaleY\":1.08,\"lookX\":-4,\"lookY\":-3,\"y\":-1},\"right\":{\"o"
            +             "pen\":1.1,\"scaleX\":1.05,\"scaleY\":1.08,\"lookX\":4,\"lookY\":-3,\"y\":-1}},\"anims\":[{\"target\":\"body\",\"prop\":"
            +             "\"x\",\"type\":\"jitter\",\"amp\":2.2,\"speed\":12,\"decay\":600},{\"target\":\"body\",\"prop\":\"rotate\",\"type\":\"sine\""
            +             ",\"amp\":1.4,\"period\":2600},{\"target\":\"eyes\",\"prop\":\"lookY\",\"type\":\"sine\",\"amp\":1.2,\"period\":1900,\"pha"
            +             "se\":0.7}]}]";

    private Emotions() { }
}
